name: WebdriverIO Test Automation
on: [workflow_dispatch]
jobs: 
 build: 
   name: Run Automation Tests
   runs-on: ubuntu-latest

   steps:
     - name: Checkout
       uses: actions/checkout@v4
    
     - name: Install 
       uses: actions/setup-node@v4
       with:
         node-version: 20
     
     - name: Install 
       run: npm install
     
     - name: Test
       run: npm run wdio:headless
      
      